version: '3.8'

services:
  strapi:
    build: .
    image: yourdockerhubuser/cookie-admin:latest
    container_name: cookie-admin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1337:1337"
    volumes:
      - ./public:/srv/strapi/public
      - ./src:/srv/strapi/src

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 300
