version: '3.8'
services:
  strapi:
    image: registry.digitalocean.com/cookie-admin:latest
    restart: always
    ports:
      - "1337:1337"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: cookie_admin_db
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
