name: Build & Publish Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCR_REGISTRY }}
          username: do
          password: ${{ secrets.DOCR_TOKEN }}

      - name: Build and push to DOCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCR_REGISTRY }}:latest
